# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
np.version.version

'1.18.5'

2) Создать нулевой вектор размера 10

In [3]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [4]:
np.full((7), 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [5]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [6]:
arr = np.random.random_sample((5))
print(arr)
print(arr[: : -1])
print(np.flip(arr))

[0.67687238 0.24482356 0.87426026 0.07364075 0.91067187]
[0.91067187 0.07364075 0.87426026 0.24482356 0.67687238]
[0.91067187 0.07364075 0.87426026 0.24482356 0.67687238]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [7]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [8]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [9]:
arr = np.diag(range(1, 5))
arr[arr == 0] = 7
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
np.zeros((5,5)) + range(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [11]:
arr = np.random.random_sample((10, 10))
mean = np.mean(arr, axis=1)
arr = arr - mean
arr

array([[ 0.17755379,  0.20201119,  0.33108038,  0.10189696,  0.02523844,
        -0.40184875, -0.11971275, -0.06728095,  0.18609161, -0.3044304 ],
       [-0.2354412 ,  0.28092807,  0.31631989,  0.00297912, -0.15561468,
        -0.461213  , -0.08273643,  0.07720044, -0.36144005, -0.09007233],
       [-0.15834362,  0.47477493,  0.12811194, -0.37889282,  0.40882826,
        -0.25618725, -0.12645834,  0.04790842,  0.17133751, -0.1330443 ],
       [-0.49147985,  0.05485321, -0.07094183,  0.18489582, -0.1145552 ,
         0.0469128 ,  0.07536135, -0.20979849,  0.23130192,  0.16527478],
       [-0.24478902, -0.28915049,  0.43082123, -0.37527557,  0.0182432 ,
         0.08931954, -0.42069194, -0.33429223, -0.09042878,  0.35251473],
       [ 0.46667113,  0.03413844, -0.09287221,  0.48089057,  0.04866831,
         0.33604029,  0.22692778, -0.49002745, -0.05442737, -0.22680298],
       [ 0.42682374, -0.06547336,  0.46112999, -0.34509082, -0.31727718,
         0.34755609, -0.28859576,  0.12471675

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [14]:
arr = np.random.random_sample((10, 10))
median = np.median(arr, axis=0)
arr = arr - median
arr

array([[ 0.40445518,  0.44414638, -0.44344932,  0.53900871,  0.32331747,
         0.4644413 ,  0.17373174,  0.16853069,  0.56256889,  0.45030225],
       [ 0.20165901,  0.44976884,  0.17721322,  0.18650521, -0.17319169,
        -0.3292188 ,  0.64078009, -0.1907634 ,  0.22396263, -0.45329645],
       [-0.17904424, -0.10058925,  0.11283497,  0.26116028, -0.07736358,
        -0.0789333 , -0.09708856,  0.04332872, -0.1686652 ,  0.32334897],
       [ 0.24479365, -0.13863396,  0.42050263, -0.17209993, -0.51263416,
         0.39363273, -0.02694714, -0.40336405,  0.3360105 , -0.01724699],
       [-0.36052788,  0.00726227, -0.12145445,  0.09327668,  0.28809371,
        -0.3069488 , -0.12880736, -0.04332872, -0.17560702,  0.36531297],
       [ 0.05635382, -0.06866129,  0.33934282, -0.22795764,  0.13221966,
         0.03540022,  0.41247835,  0.10053194, -0.25330968,  0.40191734],
       [ 0.37093638,  0.11015277, -0.36839525,  0.52472298, -0.10211188,
         0.20085142, -0.04772415,  0.35466409

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [30]:
arr = np.random.random_sample((5, 5))
max_ = np.max(arr, axis=1)
min_ = np.min(arr, axis=1)

arr = np.hstack((arr, (max_.reshape(-1, 1))))
arr = np.hstack((arr, (min_.reshape(-1, 1))))
arr

array([[0.06537396, 0.29535363, 0.58079753, 0.22531537, 0.76202921,
        0.76202921, 0.06537396],
       [0.10639866, 0.35171382, 0.9738867 , 0.93498402, 0.01309268,
        0.9738867 , 0.01309268],
       [0.55583776, 0.67864423, 0.68552468, 0.33852689, 0.96329726,
        0.96329726, 0.33852689],
       [0.66006705, 0.33168305, 0.84976425, 0.21058118, 0.73404001,
        0.84976425, 0.21058118],
       [0.13869878, 0.49512036, 0.71283865, 0.08717661, 0.97321043,
        0.97321043, 0.08717661]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [42]:
arr = np.arange(1, 51)
print(arr)
even = arr[arr % 2 == 0]
odd = arr[arr % 2 != 0]

mult = np.dot(even.reshape(5, 5), odd.reshape(5, 5).T)
print(mult)
np.linalg.inv(mult)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[  190   490   790  1090  1390]
 [  440  1240  2040  2840  3640]
 [  690  1990  3290  4590  5890]
 [  940  2740  4540  6340  8140]
 [ 1190  3490  5790  8090 10390]]


array([[-1.85318280e+12, -7.62154054e+12,  1.26329645e+13,
         5.01142392e+12, -8.16966503e+12],
       [-5.28026593e+13,  1.36665706e+14, -1.11817396e+14,
         2.48483103e+13,  3.10603878e+12],
       [ 8.31713662e+13, -1.49037659e+14,  6.43654759e+13,
        -1.43034391e+13,  1.58042562e+13],
       [-5.22023325e+11, -8.14356387e+13,  1.56189379e+14,
        -6.59837482e+13, -8.24796853e+12],
       [-2.79935008e+13,  1.01429132e+14, -1.21370423e+14,
         5.04274532e+13, -2.49266138e+12]])

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [43]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])